[package]
name = "learn_chumsky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rym_lexer = { path = "../rym/crates/rym_lexer" }
chumsky = "0.9"

[dependencies.insta]
version = "1.26"
# features = ["yaml", "ron"]
