[package]
name = "learn_chumsky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = { git = "https://github.com/zesterer/chumsky", rev = "563dee592d1e745014edd48aad01835b530bddb2" }

rym_lexer = { path = "../rym/crates/rym_lexer" }

[dependencies.insta]
version = "1.26"
# features = ["yaml", "ron"]

[dev-dependencies]
indoc = "2.0.0"
